apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: order
spec:
  type: ExternalName
  externalName: payment-app.payment.svc.cluster.local
  ports:
  - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: order
spec:
  type: ExternalName
  externalName: delivery-app.delivery.svc.cluster.local
  ports:
  - port: 80

